### ISSUE TITLE
molecule 5 failing to detect python (obsd)

### ISSUE THREAD

**Issue by charlesrocket** [ansible-community/molecule-plugins#138]
# Issue Type

- Bug report

# Molecule and Ansible details

After 5.0 release OpenBSD host facts can't detect python https://github.com/charlesrocket/essential-collection/actions/runs/4760987268/jobs/8470507361

Same behavior with `ansible_python_interpreter: auto`.
`WARNING  vagrant driver is not installed` is also new, but this is not an issue for fbsd/nbsd.

requirements file:
```
ansible
ansible-lint
docker
molecule
molecule-plugins[docker]
molecule-plugins[vagrant]
python-vagrant
```

`WARNING: molecule-plugins 23.4.0 does not provide the extra 'vagrant'` 

Not sure if this is plugin (https://github.com/ansible-community/molecule-plugins/issues/132) or molecule or both.

# Desired Behavior

Working test

# Actual Behaviour

```
  fatal: [instance]: FAILED! => {
      "ansible_facts": {},
      "changed": false,
      "failed_modules": {
          "ansible.legacy.setup": {
              "ansible_facts": {
                  "discovered_interpreter_python": "/usr/bin/python"
              },
              "failed": true,
              "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
              "module_stdout": "/bin/sh: /usr/bin/python: not found\r\n",
              "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
              "rc": 127
          }
      },
      "msg": "The following modules failed to execute: ansible.legacy.setup\n"
  }
```

**Comment by apatard** [comment]
The warning ``WARNING  vagrant driver is not installed.`` is a (broken) warning. It won't prevent things to work.
@MrFreezeex the next error message is "clearer": "Additional properties are not allowed ('lint' was unexpected)". Your issue is that molecule 5.0 remove the ``lint`` option so you have to remove it from the molecule.yml file.
@charlesrocket the molecule_vagrant warning should be fixed in git head. There was a missing extra for python-vagrant. Im not sure about why it fails to find python. Can you please provide more details about the python issue ? It may be either molecue/molecule-plugin thing or ansible bug.

**Comment by charlesrocket** [comment]
@apatard Ny first thought was molecule needs tuning for obsd 7.3 but vagrant box was still on 7.2 at that moment. Then I crossed out old plugin cache and "driver error" since fbsd/nbsd pass with that warning. So now I am not sure what is the root cause since there was codebase changes. Tried switching `gather_facts` methods but error is still the same (with extra checked locations - `auto` case). It feels like `gather_facts` issue since it should work with manual python location. Also fallback acts a bit weird when there is more than one sub dir child to check - probably irrelevant and just needs explicit ordering. I'll try to test more today with fallback/manual to rule out other deps/ports and with 4.x just in case.

**Comment by charlesrocket** [comment]
Tried to expand fallback to cover `setup-python` action ops for minor version specified cases but still no success:

```
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: auto
        ansible_interpreter_python_fallback:
          ['/usr/bin/python',
           '/usr/bin/python3',
           '/usr/local/bin/python',
           '/usr/local/bin/python3',
           '/usr/local/bin/python3.10',
           '/usr/local/bin/python3.11',
           '/usr/pkg/bin/python3']
```

**Comment by apatard** [comment]
@charlesrocket can you please provide at least the box used ? This would help me in trying to reproduce the issue

**Comment by charlesrocket** [comment]
@apatard I am testing with `generic/openbsd7` which is 7.2 https://app.vagrantup.com/generic/boxes/openbsd7 with macOS 12 github host

ci job:
```yaml
  vagrant:
    name: molecule ${{ matrix.distro }}
    runs-on: macos-12
    strategy:
      matrix:
        distro:
          - freebsd13
          - netbsd9
          - openbsd7

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'
          check-latest: true

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ matrix.distro }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ matrix.distro }}

      - name: Run Molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
```
https://github.com/charlesrocket/essential-collection/blob/trunk/.github/workflows/ci.yml

scenario https://github.com/charlesrocket/essential-collection/blob/trunk/molecule/default/molecule.yml

**Comment by charlesrocket** [comment]
Linux tests are failing now as well with docker plugin missing https://github.com/charlesrocket/essential-collection/actions/runs/4766105601/jobs/8648649610

```
 molecule-5.0.0 molecule-plugins-23.4.1
```

**Comment by charlesrocket** [comment]
So far the only way to get it working is with following deps:

```
ansible
ansible-compat==3.0.2
ansible-lint
docker
molecule==4.0.4
molecule-docker==2
molecule-vagrant==2
python-vagrant
```
